grpc:
  port: 6565

spring:
  application:
    name: demo-service
  cloud:
    consul:
#      enabled: false
      host: localhost
      port: 8500
      discovery:
        port: ${grpc.port}
        register-health-check: false
        instance-id: ${spring.application.name}-${random.value}